# Multi-stage Docker build for twemproxy with cloud zone detection
# Stage 1: Build container using Alpine (like the working example)
FROM --platform=linux/amd64 alpine:3.19 AS builder

# Install build dependencies (Alpine style)
RUN apk --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    libtool \
    yaml-dev \
    git

# Set working directory
WORKDIR /build

# Copy source code
COPY . .

# Build twemproxy (using debug=full like the working example).
# Extract the vendored yaml BEFORE autoreconf: contrib/Makefile.am declares
# `SUBDIRS = yaml-0.1.4`, so automake (run by autoreconf) needs that directory
# to already exist. configure also re-extracts it, but autoreconf runs first.
# Extracting here means the build works from a clean context with only the
# tarball (the unpacked tree is .dockerignore'd to keep the COPY context small).
RUN tar xzf contrib/yaml-0.1.4.tar.gz -C contrib && \
    autoreconf -fvi && \
    CFLAGS="-ggdb3 -O0" ./configure \
        --prefix=/usr/local \
        && \
    make -j$(nproc) && \
    make install DESTDIR=/tmp/install

# Verify the build
RUN /tmp/install/usr/local/sbin/nutcracker --version && \
    echo "Checking if stats are compiled in:" && \
    /tmp/install/usr/local/sbin/nutcracker --describe-stats | head -5

# Stage 2: Runtime container (Alpine)
FROM --platform=linux/amd64 alpine:3.19 AS runtime

# Install runtime dependencies (Alpine)
RUN apk --no-cache add \
    yaml \
    ca-certificates \
    curl \
    dumb-init \
    bash

# Create user for running twemproxy (Alpine style)
RUN adduser -D -s /bin/false twemproxy && \
    mkdir -p /var/lib/twemproxy /var/log/twemproxy /etc/twemproxy /var/run/twemproxy && \
    chown -R twemproxy:twemproxy /var/lib/twemproxy /var/log/twemproxy /etc/twemproxy /var/run/twemproxy

# Copy binary from builder
COPY --from=builder /tmp/install/usr/local/sbin/nutcracker /usr/local/sbin/

# Copy entrypoint script and set permissions
COPY docker-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh && \
    chmod +x /usr/local/sbin/nutcracker

# Create config directory (config will be generated by entrypoint)
RUN mkdir -p /etc/twemproxy

# Health check: the stats server now speaks HTTP/1.1 (with Connection: close),
# so curl works cleanly against the /health endpoint -- this verifies the stats
# server actually responds, not merely that the port is open. (The old `nc -z`
# only checked that the TCP port accepted a connection; curl previously failed
# because the server replied with raw, unframed JSON.) -f makes a non-200 a
# failure; --max-time keeps the probe bounded.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -fsS --max-time 3 http://127.0.0.1:22222/health || exit 1

# Expose ports
EXPOSE 6378 6379 22222

# Labels
LABEL maintainer="Twemproxy Enhanced" \
      version="2.1.2" \
      description="Twemproxy with cloud zone detection and latency-based routing" \
      org.opencontainers.image.title="twemproxy-enhanced" \
      org.opencontainers.image.description="Redis proxy with intelligent zone-aware routing" \
      org.opencontainers.image.source="https://github.com/coolnagour/twemproxy"

# Switch to non-root user for security
USER twemproxy

# Set entrypoint and default command (using dumb-init like working example)
ENTRYPOINT ["dumb-init", "--rewrite", "15:2", "--", "/usr/local/bin/entrypoint.sh"]
# Stats bind to 127.0.0.1 by default (see STATS_ADDR in src/nc_stats.h): the
# in-container HEALTHCHECK hits localhost, so loopback is enough. To scrape
# stats from outside the container, add "--stats-addr=0.0.0.0" here (and only
# expose port 22222 to a trusted network).
CMD ["/usr/local/sbin/nutcracker", \
     "--conf-file=/etc/twemproxy/nutcracker.yml", \
     "--output=/var/log/twemproxy/nutcracker.log", \
     "--stats-port=22222", \
     "--stats-interval=5000"]