# Multi-stage Docker build for twemproxy with cloud zone detection
# Stage 1: Build container using Alpine (like the working example)
FROM --platform=linux/amd64 alpine:3.19 AS builder

# Install build dependencies (Alpine style)
RUN apk --no-cache add \
    alpine-sdk \
    autoconf \
    automake \
    libtool \
    yaml-dev \
    git

# Set working directory
WORKDIR /build

# Copy source code
COPY . .

# Build twemproxy (using debug=full like the working example)
RUN autoreconf -fvi && \
    CFLAGS="-ggdb3 -O0" ./configure \
        --prefix=/usr/local \
        --enable-debug=full \
        && \
    make -j$(nproc) && \
    make install DESTDIR=/tmp/install

# Verify the build
RUN /tmp/install/usr/local/sbin/nutcracker --version && \
    echo "Checking if stats are compiled in:" && \
    /tmp/install/usr/local/sbin/nutcracker --describe-stats | head -5

# Stage 2: Runtime container (Alpine)
FROM --platform=linux/amd64 alpine:3.19 AS runtime

# Install runtime dependencies (Alpine)
RUN apk --no-cache add \
    yaml \
    ca-certificates \
    curl \
    dumb-init \
    bash

# Create user for running twemproxy (Alpine style)
RUN adduser -D -s /bin/false twemproxy && \
    mkdir -p /var/lib/twemproxy /var/log/twemproxy /etc/twemproxy && \
    chown twemproxy:twemproxy /var/lib/twemproxy /var/log/twemproxy /etc/twemproxy

# Copy binary from builder
COPY --from=builder /tmp/install/usr/local/sbin/nutcracker /usr/local/sbin/

# Copy entrypoint script and set permissions
COPY docker-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh && \
    chmod +x /usr/local/sbin/nutcracker

# Create config directory (config will be generated by entrypoint)
RUN mkdir -p /etc/twemproxy

# Health check
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -f http://localhost:22222 || exit 1

# Expose ports
EXPOSE 6378 6379 22222

# Labels
LABEL maintainer="Twemproxy Enhanced" \
      version="1.0.0" \
      description="Twemproxy with cloud zone detection and latency-based routing" \
      org.opencontainers.image.title="twemproxy-enhanced" \
      org.opencontainers.image.description="Redis proxy with intelligent zone-aware routing" \
      org.opencontainers.image.source="https://github.com/coolnagour/twemproxy"

# Keep as root for entrypoint (will switch users in entrypoint script)
# USER twemproxy

# Set entrypoint and default command (using dumb-init like working example)
ENTRYPOINT ["dumb-init", "--rewrite", "15:2", "--", "/usr/local/bin/entrypoint.sh"]
CMD ["/usr/local/sbin/nutcracker", \
     "--conf-file=/etc/twemproxy/nutcracker.yml", \
     "--verbose=6", \
     "--output=/var/log/twemproxy/nutcracker.log", \
     "--stats-port=22222", \
     "--stats-addr=0.0.0.0", \
     "--stats-interval=30000"]